version: '3.9'

services:

    #api1
    api-01:
        container_name: rinha-backend-api-01
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        networks:
            - rinha
        depends_on:
            - db
            - nginx
            - redis
        deploy:
            resources:
                limits:
                    cpus: '0.4'
                    memory: '0.5GB'

    #api1
    api-02:
        container_name: rinha-backend-api-02
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app1
        networks:
            - rinha
        depends_on:
            - db
            - nginx
            - redis
        deploy:
            resources:
                limits:
                    cpus: '0.4'
                    memory: '0.5GB'

    # postgres
    db:
        container_name: rinha-backend-db
        image: postgres:13.11
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            PGDATA: /var/lib/postgresql/data/db-files/
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: '0.3'
                    memory: '0.7GB'

  # nginx
    nginx:
        container_name: rinha-backend-nginx
        image: nginx:alpine
        ports:
            - "9999:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: '0.2GB'

    # redis
    redis:
        container_name: rinha-backend-redis
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - rinha
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: '0.2GB'

volumes:
    pg_data:
        driver: local

networks:
    rinha:
        driver: bridge