version: '3.9'

services:

    #api1
    api-01:
        container_name: rinha-backend-api-01
        environment:
            PORT: 9501
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        depends_on:
            - db
            - nginx
            - redis
        command: bash -c "php bin/hyperf.php start"
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: '0.4'
                    memory: '0.3GB'

    #api1
    api-02:
        container_name: rinha-backend-api-02
        environment:
            PORT: 9502
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        depends_on:
            - db
            - nginx
            - redis
            - api-01
        command: bash -c "php bin/hyperf.php start"
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: '0.4'
                    memory: '0.3GB'

    # postgres
    db:
        container_name: rinha-backend-db
        image: postgres:15.4
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        volumes:
            - ./docker/postgres/postgres.conf:/etc/postgresql.conf
            - ./docker/postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
        command: 'postgres -c config_file="/etc/postgresql.conf" -c "max_connections=450"'
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: '1.1GB'

  # nginx
    nginx:
        container_name: rinha-backend-nginx
        image: nginx:alpine
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: '0.2GB'

    # redis
    redis:
        container_name: rinha-backend-redis
        image: redis:latest
        command: redis-server --save "" --appendonly no --maxclients 20000
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: '0.2GB'
